// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/btc-indexer/proto/btc-indexer.proto

package btcindexersrv

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Request/Response messages
type SyncRequest struct {
	RecentBlocks         []*Block `protobuf:"bytes,1,rep,name=recent_blocks,json=recentBlocks,proto3" json:"recent_blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncRequest) Reset()         { *m = SyncRequest{} }
func (m *SyncRequest) String() string { return proto.CompactTextString(m) }
func (*SyncRequest) ProtoMessage()    {}
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_btc_indexer_e6885b9d3d85d89a, []int{0}
}
func (m *SyncRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncRequest.Unmarshal(m, b)
}
func (m *SyncRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncRequest.Marshal(b, m, deterministic)
}
func (dst *SyncRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncRequest.Merge(dst, src)
}
func (m *SyncRequest) XXX_Size() int {
	return xxx_messageInfo_SyncRequest.Size(m)
}
func (m *SyncRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncRequest proto.InternalMessageInfo

func (m *SyncRequest) GetRecentBlocks() []*Block {
	if m != nil {
		return m.RecentBlocks
	}
	return nil
}

type SyncResponse struct {
	// Types that are valid to be assigned to Response:
	//	*SyncResponse_BeginStream_
	//	*SyncResponse_EndStream_
	//	*SyncResponse_SyncBlock_
	//	*SyncResponse_ReorgBlock_
	Response             isSyncResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SyncResponse) Reset()         { *m = SyncResponse{} }
func (m *SyncResponse) String() string { return proto.CompactTextString(m) }
func (*SyncResponse) ProtoMessage()    {}
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_btc_indexer_e6885b9d3d85d89a, []int{1}
}
func (m *SyncResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncResponse.Unmarshal(m, b)
}
func (m *SyncResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncResponse.Marshal(b, m, deterministic)
}
func (dst *SyncResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncResponse.Merge(dst, src)
}
func (m *SyncResponse) XXX_Size() int {
	return xxx_messageInfo_SyncResponse.Size(m)
}
func (m *SyncResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SyncResponse proto.InternalMessageInfo

type isSyncResponse_Response interface {
	isSyncResponse_Response()
}

type SyncResponse_BeginStream_ struct {
	BeginStream *SyncResponse_BeginStream `protobuf:"bytes,1,opt,name=begin_stream,json=beginStream,proto3,oneof"`
}

type SyncResponse_EndStream_ struct {
	EndStream *SyncResponse_EndStream `protobuf:"bytes,2,opt,name=end_stream,json=endStream,proto3,oneof"`
}

type SyncResponse_SyncBlock_ struct {
	SyncBlock *SyncResponse_SyncBlock `protobuf:"bytes,3,opt,name=sync_block,json=syncBlock,proto3,oneof"`
}

type SyncResponse_ReorgBlock_ struct {
	ReorgBlock *SyncResponse_ReorgBlock `protobuf:"bytes,4,opt,name=reorg_block,json=reorgBlock,proto3,oneof"`
}

func (*SyncResponse_BeginStream_) isSyncResponse_Response() {}

func (*SyncResponse_EndStream_) isSyncResponse_Response() {}

func (*SyncResponse_SyncBlock_) isSyncResponse_Response() {}

func (*SyncResponse_ReorgBlock_) isSyncResponse_Response() {}

func (m *SyncResponse) GetResponse() isSyncResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *SyncResponse) GetBeginStream() *SyncResponse_BeginStream {
	if x, ok := m.GetResponse().(*SyncResponse_BeginStream_); ok {
		return x.BeginStream
	}
	return nil
}

func (m *SyncResponse) GetEndStream() *SyncResponse_EndStream {
	if x, ok := m.GetResponse().(*SyncResponse_EndStream_); ok {
		return x.EndStream
	}
	return nil
}

func (m *SyncResponse) GetSyncBlock() *SyncResponse_SyncBlock {
	if x, ok := m.GetResponse().(*SyncResponse_SyncBlock_); ok {
		return x.SyncBlock
	}
	return nil
}

func (m *SyncResponse) GetReorgBlock() *SyncResponse_ReorgBlock {
	if x, ok := m.GetResponse().(*SyncResponse_ReorgBlock_); ok {
		return x.ReorgBlock
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SyncResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SyncResponse_OneofMarshaler, _SyncResponse_OneofUnmarshaler, _SyncResponse_OneofSizer, []interface{}{
		(*SyncResponse_BeginStream_)(nil),
		(*SyncResponse_EndStream_)(nil),
		(*SyncResponse_SyncBlock_)(nil),
		(*SyncResponse_ReorgBlock_)(nil),
	}
}

func _SyncResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SyncResponse)
	// response
	switch x := m.Response.(type) {
	case *SyncResponse_BeginStream_:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BeginStream); err != nil {
			return err
		}
	case *SyncResponse_EndStream_:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EndStream); err != nil {
			return err
		}
	case *SyncResponse_SyncBlock_:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SyncBlock); err != nil {
			return err
		}
	case *SyncResponse_ReorgBlock_:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ReorgBlock); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("SyncResponse.Response has unexpected type %T", x)
	}
	return nil
}

func _SyncResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SyncResponse)
	switch tag {
	case 1: // response.begin_stream
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SyncResponse_BeginStream)
		err := b.DecodeMessage(msg)
		m.Response = &SyncResponse_BeginStream_{msg}
		return true, err
	case 2: // response.end_stream
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SyncResponse_EndStream)
		err := b.DecodeMessage(msg)
		m.Response = &SyncResponse_EndStream_{msg}
		return true, err
	case 3: // response.sync_block
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SyncResponse_SyncBlock)
		err := b.DecodeMessage(msg)
		m.Response = &SyncResponse_SyncBlock_{msg}
		return true, err
	case 4: // response.reorg_block
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SyncResponse_ReorgBlock)
		err := b.DecodeMessage(msg)
		m.Response = &SyncResponse_ReorgBlock_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _SyncResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SyncResponse)
	// response
	switch x := m.Response.(type) {
	case *SyncResponse_BeginStream_:
		s := proto.Size(x.BeginStream)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SyncResponse_EndStream_:
		s := proto.Size(x.EndStream)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SyncResponse_SyncBlock_:
		s := proto.Size(x.SyncBlock)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SyncResponse_ReorgBlock_:
		s := proto.Size(x.ReorgBlock)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type SyncResponse_BeginStream struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncResponse_BeginStream) Reset()         { *m = SyncResponse_BeginStream{} }
func (m *SyncResponse_BeginStream) String() string { return proto.CompactTextString(m) }
func (*SyncResponse_BeginStream) ProtoMessage()    {}
func (*SyncResponse_BeginStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_btc_indexer_e6885b9d3d85d89a, []int{1, 0}
}
func (m *SyncResponse_BeginStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncResponse_BeginStream.Unmarshal(m, b)
}
func (m *SyncResponse_BeginStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncResponse_BeginStream.Marshal(b, m, deterministic)
}
func (dst *SyncResponse_BeginStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncResponse_BeginStream.Merge(dst, src)
}
func (m *SyncResponse_BeginStream) XXX_Size() int {
	return xxx_messageInfo_SyncResponse_BeginStream.Size(m)
}
func (m *SyncResponse_BeginStream) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncResponse_BeginStream.DiscardUnknown(m)
}

var xxx_messageInfo_SyncResponse_BeginStream proto.InternalMessageInfo

type SyncResponse_EndStream struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncResponse_EndStream) Reset()         { *m = SyncResponse_EndStream{} }
func (m *SyncResponse_EndStream) String() string { return proto.CompactTextString(m) }
func (*SyncResponse_EndStream) ProtoMessage()    {}
func (*SyncResponse_EndStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_btc_indexer_e6885b9d3d85d89a, []int{1, 1}
}
func (m *SyncResponse_EndStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncResponse_EndStream.Unmarshal(m, b)
}
func (m *SyncResponse_EndStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncResponse_EndStream.Marshal(b, m, deterministic)
}
func (dst *SyncResponse_EndStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncResponse_EndStream.Merge(dst, src)
}
func (m *SyncResponse_EndStream) XXX_Size() int {
	return xxx_messageInfo_SyncResponse_EndStream.Size(m)
}
func (m *SyncResponse_EndStream) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncResponse_EndStream.DiscardUnknown(m)
}

var xxx_messageInfo_SyncResponse_EndStream proto.InternalMessageInfo

type SyncResponse_SyncBlock struct {
	Block                *Block   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	TxIns                []*TxIn  `protobuf:"bytes,2,rep,name=tx_ins,json=txIns,proto3" json:"tx_ins,omitempty"`
	TxOuts               []*TxOut `protobuf:"bytes,3,rep,name=tx_outs,json=txOuts,proto3" json:"tx_outs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncResponse_SyncBlock) Reset()         { *m = SyncResponse_SyncBlock{} }
func (m *SyncResponse_SyncBlock) String() string { return proto.CompactTextString(m) }
func (*SyncResponse_SyncBlock) ProtoMessage()    {}
func (*SyncResponse_SyncBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_btc_indexer_e6885b9d3d85d89a, []int{1, 2}
}
func (m *SyncResponse_SyncBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncResponse_SyncBlock.Unmarshal(m, b)
}
func (m *SyncResponse_SyncBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncResponse_SyncBlock.Marshal(b, m, deterministic)
}
func (dst *SyncResponse_SyncBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncResponse_SyncBlock.Merge(dst, src)
}
func (m *SyncResponse_SyncBlock) XXX_Size() int {
	return xxx_messageInfo_SyncResponse_SyncBlock.Size(m)
}
func (m *SyncResponse_SyncBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncResponse_SyncBlock.DiscardUnknown(m)
}

var xxx_messageInfo_SyncResponse_SyncBlock proto.InternalMessageInfo

func (m *SyncResponse_SyncBlock) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *SyncResponse_SyncBlock) GetTxIns() []*TxIn {
	if m != nil {
		return m.TxIns
	}
	return nil
}

func (m *SyncResponse_SyncBlock) GetTxOuts() []*TxOut {
	if m != nil {
		return m.TxOuts
	}
	return nil
}

type SyncResponse_ReorgBlock struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	OldHash              string   `protobuf:"bytes,2,opt,name=old_hash,json=oldHash,proto3" json:"old_hash,omitempty"`
	NewHash              string   `protobuf:"bytes,3,opt,name=new_hash,json=newHash,proto3" json:"new_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncResponse_ReorgBlock) Reset()         { *m = SyncResponse_ReorgBlock{} }
func (m *SyncResponse_ReorgBlock) String() string { return proto.CompactTextString(m) }
func (*SyncResponse_ReorgBlock) ProtoMessage()    {}
func (*SyncResponse_ReorgBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_btc_indexer_e6885b9d3d85d89a, []int{1, 3}
}
func (m *SyncResponse_ReorgBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncResponse_ReorgBlock.Unmarshal(m, b)
}
func (m *SyncResponse_ReorgBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncResponse_ReorgBlock.Marshal(b, m, deterministic)
}
func (dst *SyncResponse_ReorgBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncResponse_ReorgBlock.Merge(dst, src)
}
func (m *SyncResponse_ReorgBlock) XXX_Size() int {
	return xxx_messageInfo_SyncResponse_ReorgBlock.Size(m)
}
func (m *SyncResponse_ReorgBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncResponse_ReorgBlock.DiscardUnknown(m)
}

var xxx_messageInfo_SyncResponse_ReorgBlock proto.InternalMessageInfo

func (m *SyncResponse_ReorgBlock) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *SyncResponse_ReorgBlock) GetOldHash() string {
	if m != nil {
		return m.OldHash
	}
	return ""
}

func (m *SyncResponse_ReorgBlock) GetNewHash() string {
	if m != nil {
		return m.NewHash
	}
	return ""
}

// Data messages
type Block struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	PreviousHash         string   `protobuf:"bytes,3,opt,name=previous_hash,json=previousHash,proto3" json:"previous_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_btc_indexer_e6885b9d3d85d89a, []int{2}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Block) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Block) GetPreviousHash() string {
	if m != nil {
		return m.PreviousHash
	}
	return ""
}

type TxIn struct {
	TxHash               string   `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	TxIndex              int32    `protobuf:"varint,2,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
	Height               int64    `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	PreviousTxHash       string   `protobuf:"bytes,5,opt,name=previous_tx_hash,json=previousTxHash,proto3" json:"previous_tx_hash,omitempty"`
	PreviousTxIndex      int32    `protobuf:"varint,6,opt,name=previous_tx_index,json=previousTxIndex,proto3" json:"previous_tx_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxIn) Reset()         { *m = TxIn{} }
func (m *TxIn) String() string { return proto.CompactTextString(m) }
func (*TxIn) ProtoMessage()    {}
func (*TxIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_btc_indexer_e6885b9d3d85d89a, []int{3}
}
func (m *TxIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxIn.Unmarshal(m, b)
}
func (m *TxIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxIn.Marshal(b, m, deterministic)
}
func (dst *TxIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxIn.Merge(dst, src)
}
func (m *TxIn) XXX_Size() int {
	return xxx_messageInfo_TxIn.Size(m)
}
func (m *TxIn) XXX_DiscardUnknown() {
	xxx_messageInfo_TxIn.DiscardUnknown(m)
}

var xxx_messageInfo_TxIn proto.InternalMessageInfo

func (m *TxIn) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *TxIn) GetTxIndex() int32 {
	if m != nil {
		return m.TxIndex
	}
	return 0
}

func (m *TxIn) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *TxIn) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *TxIn) GetPreviousTxHash() string {
	if m != nil {
		return m.PreviousTxHash
	}
	return ""
}

func (m *TxIn) GetPreviousTxIndex() int32 {
	if m != nil {
		return m.PreviousTxIndex
	}
	return 0
}

type TxOut struct {
	TxHash               string   `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	TxIndex              int32    `protobuf:"varint,2,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
	Height               int64    `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Value                int64    `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	ScriptPubKey         string   `protobuf:"bytes,6,opt,name=script_pub_key,json=scriptPubKey,proto3" json:"script_pub_key,omitempty"`
	CoinBase             bool     `protobuf:"varint,7,opt,name=coin_base,json=coinBase,proto3" json:"coin_base,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxOut) Reset()         { *m = TxOut{} }
func (m *TxOut) String() string { return proto.CompactTextString(m) }
func (*TxOut) ProtoMessage()    {}
func (*TxOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_btc_indexer_e6885b9d3d85d89a, []int{4}
}
func (m *TxOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxOut.Unmarshal(m, b)
}
func (m *TxOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxOut.Marshal(b, m, deterministic)
}
func (dst *TxOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxOut.Merge(dst, src)
}
func (m *TxOut) XXX_Size() int {
	return xxx_messageInfo_TxOut.Size(m)
}
func (m *TxOut) XXX_DiscardUnknown() {
	xxx_messageInfo_TxOut.DiscardUnknown(m)
}

var xxx_messageInfo_TxOut proto.InternalMessageInfo

func (m *TxOut) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *TxOut) GetTxIndex() int32 {
	if m != nil {
		return m.TxIndex
	}
	return 0
}

func (m *TxOut) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *TxOut) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *TxOut) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *TxOut) GetScriptPubKey() string {
	if m != nil {
		return m.ScriptPubKey
	}
	return ""
}

func (m *TxOut) GetCoinBase() bool {
	if m != nil {
		return m.CoinBase
	}
	return false
}

func init() {
	proto.RegisterType((*SyncRequest)(nil), "btcindexersrv.SyncRequest")
	proto.RegisterType((*SyncResponse)(nil), "btcindexersrv.SyncResponse")
	proto.RegisterType((*SyncResponse_BeginStream)(nil), "btcindexersrv.SyncResponse.BeginStream")
	proto.RegisterType((*SyncResponse_EndStream)(nil), "btcindexersrv.SyncResponse.EndStream")
	proto.RegisterType((*SyncResponse_SyncBlock)(nil), "btcindexersrv.SyncResponse.SyncBlock")
	proto.RegisterType((*SyncResponse_ReorgBlock)(nil), "btcindexersrv.SyncResponse.ReorgBlock")
	proto.RegisterType((*Block)(nil), "btcindexersrv.Block")
	proto.RegisterType((*TxIn)(nil), "btcindexersrv.TxIn")
	proto.RegisterType((*TxOut)(nil), "btcindexersrv.TxOut")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BtcIndexerClient is the client API for BtcIndexer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BtcIndexerClient interface {
	Sync(ctx context.Context, opts ...grpc.CallOption) (BtcIndexer_SyncClient, error)
}

type btcIndexerClient struct {
	cc *grpc.ClientConn
}

func NewBtcIndexerClient(cc *grpc.ClientConn) BtcIndexerClient {
	return &btcIndexerClient{cc}
}

func (c *btcIndexerClient) Sync(ctx context.Context, opts ...grpc.CallOption) (BtcIndexer_SyncClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BtcIndexer_serviceDesc.Streams[0], "/btcindexersrv.BtcIndexer/Sync", opts...)
	if err != nil {
		return nil, err
	}
	x := &btcIndexerSyncClient{stream}
	return x, nil
}

type BtcIndexer_SyncClient interface {
	Send(*SyncRequest) error
	Recv() (*SyncResponse, error)
	grpc.ClientStream
}

type btcIndexerSyncClient struct {
	grpc.ClientStream
}

func (x *btcIndexerSyncClient) Send(m *SyncRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *btcIndexerSyncClient) Recv() (*SyncResponse, error) {
	m := new(SyncResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BtcIndexerServer is the server API for BtcIndexer service.
type BtcIndexerServer interface {
	Sync(BtcIndexer_SyncServer) error
}

func RegisterBtcIndexerServer(s *grpc.Server, srv BtcIndexerServer) {
	s.RegisterService(&_BtcIndexer_serviceDesc, srv)
}

func _BtcIndexer_Sync_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BtcIndexerServer).Sync(&btcIndexerSyncServer{stream})
}

type BtcIndexer_SyncServer interface {
	Send(*SyncResponse) error
	Recv() (*SyncRequest, error)
	grpc.ServerStream
}

type btcIndexerSyncServer struct {
	grpc.ServerStream
}

func (x *btcIndexerSyncServer) Send(m *SyncResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *btcIndexerSyncServer) Recv() (*SyncRequest, error) {
	m := new(SyncRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _BtcIndexer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "btcindexersrv.BtcIndexer",
	HandlerType: (*BtcIndexerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sync",
			Handler:       _BtcIndexer_Sync_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "srv/btc-indexer/proto/btc-indexer.proto",
}

func init() {
	proto.RegisterFile("srv/btc-indexer/proto/btc-indexer.proto", fileDescriptor_btc_indexer_e6885b9d3d85d89a)
}

var fileDescriptor_btc_indexer_e6885b9d3d85d89a = []byte{
	// 589 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x75, 0xec, 0xc4, 0xe3, 0xa4, 0xc0, 0x52, 0x81, 0x71, 0x2f, 0x55, 0xf8, 0x68, 0x54,
	0xa9, 0x29, 0x2a, 0x27, 0xae, 0x41, 0xa0, 0x46, 0x20, 0x01, 0xdb, 0x1e, 0x10, 0x17, 0xcb, 0x1f,
	0xab, 0xc6, 0x6a, 0x58, 0x87, 0xdd, 0x75, 0xea, 0xfc, 0x0d, 0x7e, 0x12, 0x07, 0xce, 0xfc, 0x24,
	0xb4, 0xb3, 0x71, 0xe2, 0x54, 0x51, 0xb8, 0x70, 0x4a, 0xde, 0xec, 0xf3, 0x9b, 0xf7, 0x66, 0xd6,
	0x86, 0x63, 0x29, 0xe6, 0x67, 0x89, 0x4a, 0x4f, 0x73, 0x9e, 0xb1, 0x8a, 0x89, 0xb3, 0x99, 0x28,
	0x54, 0xd1, 0xac, 0x0c, 0xb1, 0x42, 0x7a, 0x89, 0x4a, 0x97, 0x15, 0x29, 0xe6, 0xfd, 0x0b, 0xf0,
	0x2f, 0x17, 0x3c, 0xa5, 0xec, 0x47, 0xc9, 0xa4, 0x22, 0x6f, 0xa0, 0x27, 0x58, 0xca, 0xb8, 0x8a,
	0x92, 0x69, 0x91, 0xde, 0xc8, 0xc0, 0x3a, 0xb2, 0x07, 0xfe, 0xf9, 0xc1, 0x70, 0xe3, 0xa9, 0xe1,
	0x48, 0x1f, 0xd2, 0xae, 0xa1, 0x22, 0x90, 0xfd, 0x3f, 0x2d, 0xe8, 0x1a, 0x29, 0x39, 0x2b, 0xb8,
	0x64, 0xe4, 0x23, 0x74, 0x13, 0x76, 0x9d, 0xf3, 0x48, 0x2a, 0xc1, 0xe2, 0xef, 0x81, 0x75, 0x64,
	0x0d, 0xfc, 0xf3, 0xe3, 0x3b, 0x52, 0xcd, 0x47, 0x86, 0x23, 0xcd, 0xbf, 0x44, 0xfa, 0xc5, 0x3d,
	0xea, 0x27, 0x6b, 0x48, 0xde, 0x03, 0x30, 0x9e, 0xd5, 0x5a, 0x7b, 0xa8, 0xf5, 0x62, 0x97, 0xd6,
	0x3b, 0x9e, 0xad, 0x94, 0x3c, 0x56, 0x03, 0xad, 0x23, 0x17, 0x3c, 0x35, 0xf9, 0x02, 0xfb, 0xdf,
	0x3a, 0x1a, 0x60, 0x44, 0xad, 0x23, 0x6b, 0x40, 0xc6, 0xe0, 0x0b, 0x56, 0x88, 0xeb, 0xa5, 0x50,
	0x0b, 0x85, 0x5e, 0xee, 0x12, 0xa2, 0x9a, 0x5e, 0x2b, 0x81, 0x58, 0xa1, 0xb0, 0x07, 0x7e, 0x23,
	0x78, 0xe8, 0x83, 0xb7, 0xf2, 0x1e, 0xfe, 0xb4, 0xc0, 0x5b, 0x39, 0x20, 0x27, 0xe0, 0x98, 0x76,
	0x66, 0x96, 0xdb, 0xd7, 0x62, 0x28, 0xe4, 0x04, 0x5c, 0x55, 0x45, 0x39, 0x97, 0xc1, 0x1e, 0xee,
	0xf0, 0xd1, 0x1d, 0xf2, 0x55, 0x35, 0xe6, 0xd4, 0x51, 0xd5, 0x98, 0x4b, 0x72, 0x0a, 0x6d, 0x55,
	0x45, 0x45, 0xa9, 0x64, 0x60, 0x6f, 0x5d, 0xf8, 0x55, 0xf5, 0xa9, 0x54, 0xd4, 0x55, 0xfa, 0x47,
	0x86, 0xdf, 0x00, 0xd6, 0x61, 0xc8, 0x63, 0x70, 0x27, 0x2c, 0xbf, 0x9e, 0x28, 0x74, 0x65, 0xd3,
	0x25, 0x22, 0x4f, 0xa1, 0x53, 0x4c, 0xb3, 0x68, 0x12, 0xcb, 0x09, 0xee, 0xcb, 0xa3, 0xed, 0x62,
	0x9a, 0x5d, 0xc4, 0x72, 0xa2, 0x8f, 0x38, 0xbb, 0x35, 0x47, 0xb6, 0x39, 0xe2, 0xec, 0x56, 0x1f,
	0x8d, 0x00, 0x3a, 0x62, 0x39, 0xb1, 0xfe, 0x57, 0x70, 0x76, 0xb7, 0x20, 0xd0, 0x6a, 0xc8, 0xe3,
	0x7f, 0xf2, 0x0c, 0x7a, 0x33, 0xc1, 0xe6, 0x79, 0x51, 0xca, 0x66, 0x83, 0x6e, 0x5d, 0xd4, 0x5d,
	0xfa, 0xbf, 0x2c, 0x68, 0xe9, 0x01, 0x90, 0x27, 0x98, 0x1c, 0x79, 0x16, 0xf2, 0x5c, 0x55, 0xd5,
	0x16, 0x71, 0x7c, 0x19, 0xab, 0x50, 0xde, 0xa1, 0x6d, 0x3d, 0xab, 0x8c, 0x55, 0x0d, 0x37, 0xf6,
	0x86, 0x9b, 0x00, 0xda, 0x71, 0x96, 0x09, 0x26, 0x25, 0x5e, 0x07, 0x8f, 0xd6, 0x90, 0x0c, 0xe0,
	0xc1, 0xca, 0x53, 0xdd, 0xce, 0x41, 0xca, 0x7e, 0x5d, 0xbf, 0x32, 0x6d, 0x4f, 0xe0, 0x61, 0x93,
	0x69, 0xfa, 0xbb, 0xd8, 0xff, 0xfe, 0x9a, 0x8a, 0x3e, 0xfa, 0xbf, 0x2d, 0x70, 0x70, 0x31, 0xff,
	0x35, 0xc5, 0x01, 0x38, 0xf3, 0x78, 0x5a, 0x32, 0xcc, 0x60, 0x53, 0x03, 0x9a, 0xd9, 0x9c, 0xcd,
	0x6c, 0xcf, 0x61, 0x5f, 0xa6, 0x22, 0x9f, 0xa9, 0x68, 0x56, 0x26, 0xd1, 0x0d, 0x5b, 0xa0, 0x5d,
	0x8f, 0x76, 0x4d, 0xf5, 0x73, 0x99, 0x7c, 0x60, 0x0b, 0x72, 0x08, 0x5e, 0x5a, 0xe4, 0x3c, 0x4a,
	0x62, 0xc9, 0x82, 0xf6, 0x91, 0x35, 0xe8, 0xd0, 0x8e, 0x2e, 0x8c, 0x62, 0xc9, 0xce, 0xbf, 0x00,
	0x8c, 0x54, 0x3a, 0x36, 0xd7, 0x8d, 0xbc, 0x85, 0x96, 0xbe, 0xf1, 0x24, 0xdc, 0xfa, 0x32, 0xe1,
	0x77, 0x2a, 0x3c, 0xdc, 0xf1, 0xa2, 0x0d, 0xac, 0x57, 0x56, 0xe2, 0xe2, 0xd7, 0xee, 0xf5, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x1b, 0x3f, 0x76, 0x18, 0x05, 0x00, 0x00,
}
